# Site settings
title: ntp. - Code, rants and rock'n'roll.
owner: Nils Torbjörn Petersen, M.A.
email: kontakt@entepe.de
description: > # this means to ignore newlines until "baseurl:"
    Blog und digitale Visitenkarte von Nils Torbjörn Petersen. Webentwickler, Musiker und ambitionierter Hobby-Fotograf aus Kiel an der schönen Ostseeküste.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://entepe.de" # the base hostname & protocol for your site
twitter_username: DerNerddeutsche
github_username:  entepe85
instagram_username: der_nerddeutsche

# Build settings
markdown: kramdown
sass:
    style: compressed
